name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - name: Check Version
        shell: bash
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/}"
          TAG_VERSION="${TAG_VERSION#v}"
          echo "Tag Version: $TAG_VERSION"
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Package Version: $PACKAGE_VERSION"
          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Tag version and package version do not match!"
            exit 1
          fi
      - name: Publish
        run: |
          npm install
          npm publish
